# 站点设置
site:
  name: ADMS              # 左上角首页名称
  icon: /img/avatar.webp  # 页脚的icon
  icp:                    # ICP
  siteIcon: /img/avatar.webp # 主页的icon

# 导航栏
nav:
#导航栏左侧
  left:
    enable: true
    menu:
      我的:
        博客:
          icon: /img/avatar.webp
          url: /
# 导航栏内容
  menu:
     文库:
       url: false
       child:
         文章列表:
           url: /archives/
           icon: fas fa-box-archive
         全部分类:
           url: /categories/
           icon: fas fa-cube
         全部标签:
           url: /tags/
           icon: fas fa-tags
     友链:
       url: false
       child:
         友链鱼塘:
           url: /fcircle/
           icon: fas fa-fish-fins
         友情链接:
           url: /links/
           icon: fas fa-user-group
         宝藏博主:
           url: javascript:travelling()
           icon: fas fa-bus

# 导航栏右侧快捷菜单
  right: # @todo 允许用户自定义
    travellings: true   #开往
    random: true        #
    search: false       #刷新按钮
    console: true       #控制台

# heo式顶部一大坨
hometop:
  bbtime: true
  banner:
    title: 分享设计<br>与技术生活
    url: 阿德密斯
    icon:
      AE:
        img: /img/icon/ae.png
        color: '#989bf8'
      Sketch:
        img: /img/icon/Sketch.png
        color: '#ffffff'
      Docker:
        img: /img/icon/docker.png
        color: '#57b6e6'
      ps:
        img: /img/icon/ps.png
        color: '#4082c3'
      FinalCutPro:
        img: /img/icon/FinalCutPro.png
        color: '#ffffff'
      Python:
        img: /img/icon/Python.png
        color: '#ffffff'
      Swift:
        img: /img/icon/Swift.png
        color: '#eb6840'
      Principle:
        img: /img/icon/Principle.png
        color: '#8f55ba'
      illustrator:
        img: /img/icon/illustrator.png
        color: '#f29e39'
      CSS3:
        img: /img/icon/CSS3.png
        color: '#2c51db'
      JS:
        img: /img/icon/JS.png
        color: '#f7cb4f'
      Git:
        img: /img/icon/git.png
        color: '#df5b40'

  categoryGroup:
    G1:
      name: 现在的项目
      icon: fas fa-dove
      url: /tags/PULPino/
    G2:
      name: 热门文章
      icon: fas fa-burn
      url: /tags/RISCV/
    G3:
      name: 实用教程
      icon: fas fa-book
      url: /tags/工具/

  recommendList:
    sup: 阿德密斯
    title: 用技术改变生活
    url: /
    img: /img/排球.jpg
    color: '#006a73'

# 个人卡片
aside:
  card:
    content: 这有关于<b>RSIC-V</b>、<b>芯片设计</b>、<b>系统开发管理</b>的技术探究，还有对于生活的一些<b>想法</b>。<br>这里是我的仓库。
    information:
      Github:
        icon: fa-brands fa-github
        url: https://github.com/AdmsLCW
      Mail:
        icon: fa-solid fa-envelope
        url: mailto:2118974983@qq.com
    button:
      text: 个人主页
      url: /about
# 建站时间
  analytics:
    runtime: '2023-3-28 00:00:00'

# 页脚
footer:
  information:
    left:
      Github:
        icon: fa-brands fa-github
        url: https://github.com/AdmsLCW
      Mail:
        icon: fa-solid fa-envelope
        url: mailto:2118974983@qq.com
    right:
      网易云:
        icon: fa-solid fa-music
        url: https://music.163.com
      bilibili:
        icon: fa-brands fa-bilibili
        url: https://www.bilibili.com

  group:
    导航:
      文章归档: /archives/
      文章分类: /categories/
      文章标签: /tags/
      友链: /link/
    服务:
      51la统计: https://51.la/
      百度统计: https://tongji.baidu.com/
      TianliCDN: https://ql.tianli0.top/
    Acrylic:
      主题官网: https://acrylic.zhheo.com/
      Github: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic
      Heo: https://blog.zhheo.com/
    推荐友链:
      Heo: https://blog.zhheo.com/
      Akilar: https://akilar.top

  randomlink: false

# 文章页默认设置
post:
  default:
    cover: /img/hello.jpg
    locate: 武汉
    copyright: 原创
    excerpt: 100
    covercolor: true  #文章cover取色
  award:
    enable: false
    wechat:
    alipay:
    url:

# 404
errorpage:
  img: /img/acrylic.png
  text: =awa= 页面走丢了
  recommendList: true

# 懒加载
lazyload:
  enable: true
  placeholder: /img/acrylic.png
  errorimg: /img/acrylic.png

# 加载动画
loading:
  enable: true
  pace: true

# 第三方设置
thirdparty:
  wordcount: true

# 评论
comment:
  enable: true
  twikoo:
    envId: https://twik-three.vercel.app




# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends: 
  head: # 在head中插入
    # - <script></script>
  body: # 在body中插入

# 非必要勿动
cdn:
  head:
    pacejs: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    fontawesomecss: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.min.css
    snackbarcss: /lib/snackbar.min.css
    qrcodejs: /lib/qrcode.min.js
    twikoojs: https://cdn.staticfile.org/twikoo/1.6.10/twikoo.all.min.js
  body:
    swipercss: /lib/swiper.min.css
    pjaxjs: /lib/pjax.min.js
    lazyloadjs: /lib/lazyload.min.js
    snackbarjs: /lib/snackbar.min.js
    viewimagejs: /lib/view-image.min.js
    waterfalljs: /lib/waterfall.min.js
    swiperjs: /lib/swiper.min.js